# Generated by Django 4.2.1 on 2023-06-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0010_alter_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='modify_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='modify_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='modify_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
